[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.3"
tokio = "1.32.0"
tungstenite = "0.20.0"

[dependencies.rocket_dyn_templates]
version = "=0.1.0-rc.3"
features = ["handlebars", "tera"]
