[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
yew-websocket = "1.0.1"

[dependencies.yew]
version = "0.20.0"
features = ["csr"]
